config/routes.rb
CodebuddiesRails::Application.routes.draw do

     resources :hangoutevents
     root :to =>   'hangoutevents#index'

end

app/models/hangoutevent.rb
# == Schema Information
#
# Table name: hangoutevents
#
#  id              :integer          not null, primary key
#  title           :string(255)
#  start_date      :datetime
#  end_date        :datetime
#  start_date_day  :string(255)
#  start_date_time :string(255)
#  end_date_day    :string(255)
#  end_date_time   :string(255)
#  language_id     :integer
#  level           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  description     :text
#

class Hangoutevent < ActiveRecord::Base
  attr_accessible :end_date, :end_date_day, :end_date_time, :language, :level, :start_date, :start_date_day, :start_date_time, :title, :description

  after_create :create_google_calendar_event

  def create_google_calendar_event
  	
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/hangoutevents_controller.rb
class HangouteventsController < ApplicationController
	def index
		@event = Hangoutevent.all
	end

	def new
	  # binding.pry
	  @event = Hangoutevent.new
	end

	def create
		# binding.pry
		Hangoutevent.create(params[:hangoutevent])

		#Hangoutevent.create(hangoutevent_params)
		redirect_to hangoutevents_path
	end

	def show
		redirect_to hangoutevents_path
	end

	def destroy
		@event = Hangoutevent.find(params[:id])
		@event.destroy
		redirect_to hangoutevents_path
	end

	def edit
		@event = Hangoutevent.find(params[:id])
	end

	def update
		@event = Hangoutevent.find(params[:id])
		@event.update_attributes(params[:hangoutevent])
		redirect_to hangoutevents_path
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/hangoutevents/_form.html.haml
<h1>Propose A New Hangout</h1>
/ Database column names
/ 	  t.string   "title"
/     t.datetime "start_date"
/     t.datetime "end_date"
/     t.string   "start_date_day"
/     t.string   "start_date_time"
/     t.string   "end_date_day"
/     t.string   "end_date_time"
/     t.integer  "language_id"
/     t.string   "level"
/     t.datetime "created_at",      :null => false
/     t.datetime "updated_at",      :null => false
/     t.text     "description"

= simple_form_for @event do |form|
	.row		
		= form.input :title
	.row
		= form.input :start_date, as: :date, start_year: Date.today.year, end_year: Date.today.year + 1, order: [:month, :day, :year]
	.row
		= form.label :start_date_time, "Start Time:"
		= form.select("start_date_time", {"11:30 am" => "11:30 am", "12:30 pm" => "12:30 pm"})
	.row
		= form.input :description
	.row
		.actions
		= form.submit 'Propose Hangout', class: 'green button large padded fixed center'
	
%br
%br
%br

app/views/hangoutevents/edit.html.haml
= render "form"

app/views/hangoutevents/index.html.erb
<h1>Your Current Hangouts</h1>
<% @event.each do |event| %>
	<h3><%= event.title%></h3>
	<p><%= event.description%></p>
	<p><%= event.start_date %></p>
	<h5 id="edit"><%= link_to "Edit Hangout", edit_hangoutevent_path(event) %></h5>
	<h5 id="delete"><%= link_to "Delete Hangout", event, method: :delete %></h5>
<% end %>

app/views/hangoutevents/new.html.haml
= render "form"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Codebuddies</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
<header>
	<div class="left-nav">
		<ul>
			<li><%= link_to "Home", hangoutevents_path%></li>
		</ul>
	</div>
	<div class="right-nav">
		<ul>
			<li><%= link_to "Propose Hangout", new_hangoutevent_path%></li>
		</ul>
	</div>
	<div class="clearfix"></div>
</header>

<%= yield %>

</body>
</html>

app/views/pages/home.html.haml
CodeBuddies